Comments/urls.py
from django.urls import path
from . import views

app_name = 'Comments'

urlpatterns = [
    path('<int:id>/', views.comments, name='Comments'),
    path ('<int:id>/data/',views.comments_data, name='Comments_data'),
    path('display/<int:id>/', views.displayComments, name='DisplayComments'),
    path ('display/<int:id>/data/',views.displayComments_data, name='DisplayComments_data'),
]

homepage/urls.py
from django.urls import path
from django.contrib.auth import views as av
from .views import register
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name="home"),
    path('user-type/', views.user_type, name='user_type'),
    path('login/', av.LoginView.as_view(template_name='auth.html'), name='auth'),
    path('logout/', av.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', register, name='register'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('Merch/', include('Merchandise.urls')),
    path('RegisterEvent/', include('RegisterEvent.urls')),
    path('Comments/', include('Comments.urls')),
    path('CreateEvent/', include('CreateEvent.urls')),
] 

Comments/models.py
from django.db import models
from CreateEvent.models import Event
from django.contrib.auth.models import User
# Create your models here.

class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.CharField(max_length=500)


    def __str__(self):
        return self.name

Comments/forms.py
from django.forms import ModelForm, TextInput
from .models import Comments


class CommentsForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'comment']
        widgets = {
            'name': TextInput(attrs={'placeholder': 'Eros','id':'name','required': True}),
            'comment': TextInput(attrs={'placeholder': 'Comment here','id':'comment','required': True})
        }

Comments/views.py
import json
from django.shortcuts import render,redirect
from django.http.response import HttpResponse, JsonResponse
from .forms import CommentsForm
from .models import Comments
from django.contrib import messages
from CreateEvent.models import Event
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

# def displayComments(request, id):
    
#     event = Event.objects.get(id=id)
#     commentsValue = Comments.objects.all()
#     context = {'event': event, 'commentsValue': commentsValue}

#     return render(request, 'Comments/displayComments.html', context)

def displayComments(request,id):
    event = Event.objects.get(id=id)
    context = {'event':event}
    return render(request, 'Comments/displayComments.html',context)

def displayComments_data(request,id):
    data =[]
    event = Event.objects.get(id=id)
    commentsValue = Comments.objects.all()
    for i in commentsValue :
        if i.event.eventName == event.eventName :
            temp = dict()
            temp['id'] = i.id
            temp['name'] = i.name
            temp["comment"] = i.comment 
            data.append(temp)

    context = {'data':data}
    return JsonResponse(context)

@login_required(login_url=reverse_lazy('homepage:auth'))
def comments(request,id):
    form = CommentsForm(request.POST or None)
    context = {'form':form}
    return render(request, 'Comments/index.html', context)

def comments_data(request,id):
    if request.method == 'POST':
        event = Event.objects.get(id=id)
        
        name = request.POST.get('name')
        comment = request.POST.get('comments')

        response_data = dict()
        
        # print(name)
        # print(comment)
        post = Comments(user = request.user,event=event,name=name,comment=comment)
        post.save()

        response_data['result'] = 'Create post successful'

        return JsonResponse(response_data)


              
# def comments(request, id):
#     form = CommentsForm(request.POST or None)
#     if form.is_valid():
#         obj = form.save(commit=False)
#         obj.event = Event.objects.get(id=id)
#         messages.success(request, f"Comment Sucesfully Added")
#         form.instance.event_id = id
#         form.instance.user = request.user
#         form.save()
#         return redirect("CreateEvent:ViewEvent")
#     context = {'form':form}
#     return render(request, 'Comments/index.html', context)

Comments/templates/Comments/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/base.css' %}">
        <script src="{% static 'js/base.js' %}" defer></script>
        <title>PEPEWIN</title>
    </head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-light" >
    <a class="navbar-brand" href="{% url 'homepage:home' %} " style="color: black;">LOGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:user_type' %}" style="color: black;">Events<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">About Us<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">Our Contacts</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <div class="custom-control custom-switch" id="cssMode" style="padding-top: 5%;">
          <input type="checkbox" class="custom-control-input" id="customSwitch1">
          <label class="custom-control-label" id="switch" for="customSwitch1"></label>
        </div>
        {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style="color: black;"> Hello, {{ user.username }} </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:logout' %}" style="color: black;">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:auth' %}" style="color: black;">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:register' %}" style="color: black;"> Register</a>
                </li>
            {% endif %}                      
      </ul>
    </div>
  </nav>




    {% block content %}
        
    {% endblock %}
     
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
  
  {% block extrascript %}
    
  {% endblock %}
    
</body>
</html>

Comments/templates/Comments/displayComments.html
{% extends 'Comments/base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<style>
    .dark-mode{
        background-image: linear-gradient(118deg, #383686 0%, #13547A 98.85%);
        background-attachment: fixed;
    }
    .a-on-hover{
        color: red;
    }
</style>

    <br>
    {% if messages %}
            {% for i in messages %}
            <br>
            <div class="alert alert-secondary" role="alert">
                {{ i }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% endfor %}
        {% endif %}


    {% if event  %}
        <div class="container-fluid">
            <div class="card mb-4 mx-5 entry">
                <div class="card-header">
                    <div class="row">
                        <div class="col" id="title"><p>{{event.eventName}}</p></div>
                        <a style="display: inline;padding-right: 2%;" href="{% url 'Comments:Comments' id=event.id %}">
                            <button type="button" class="btn btn-outline-secondary">Comment</button>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                     
                     <!-- {% for j in commentsValue %}
                         
                         {% if j.event.eventName == event.eventName %}

                         
                         {% endif %}
                         
                         {% endfor %} -->
                         
                         <div id="comments">
     
                         </div>

                        <!-- {% for j in commentsValue %}
                        {% if j.event.eventName == event.eventName %}
                            <div class="card mb-4" style="width: auto;">
                                <div class="row">
                                    <div class="col">
                                        <p style="font-weight: bold;">{{j.name}}</p>
                                    </div>
                                    <div class="col">
                                        <a href="#" class="up" style="display: inline-block; float: right;padding-right: 5%;">UP</a>
                                        <a href="#" class="down" style="display: inline-block; float: right; padding-right: 5%;">DOWN</a>
                                    </div>
                                </div>
                                <p >{{ j.comment }}</p>
                            </div>
                        {% endif %}
                        {% endfor %} -->
                    
                </div>
            </div>
        </div>
        {% endif %}
        
        {% endblock %}

        
        {% block extrascript %}
        <script src="{% static 'js/comment.js' %}" defer></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'js/ajax.js' %}" defer></script>
        {% endblock %}

Comments/templates/Comments/index.html
{% extends 'Comments/base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <style>
        .container{
            width: 100%;
        }
        .dark-mode{
        background-image: linear-gradient(118deg, #383686 0%, #13547A 98.85%);
        background-attachment: fixed;
        color: white;
        }
        .h3-dark{
            color: white;
        }
    </style>
    <body>
        <br>
        
        <div class="container">
            <h3 style="text-align: center;">You have Inputted <span id="span-num"> 0 </span> amount of words on the current text field</h3>
            <br>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-light" type="submit" value="Submit" id="submit">
            </form> 
        </div>
    </body>
{% endblock %}

{% block extrascript %}
<script src="{% static 'js/comment.js' %}" defer></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/createcomment.js' %}" defer></script>
{% endblock %}