Merchandise/urls.py
from django.urls import path

from . import views

app_name = 'Merchandise'

urlpatterns = [
    path('RegisterMerch/<int:id>/', views.registerMerch, name='RegisterMerch'),
    path('ListMerch/<int:id>/', views.displayMerch, name='ListMerch'),
    path('ListMerch/json/<int:id>/', views.MerchApi, name='MerchJson'),
    path('RegisterMerchAjax/<int:id>/', views.ajaxMerch, name='RegisterMerchAjax'),

]

homepage/urls.py
from django.urls import path
from django.contrib.auth import views as av
from .views import register
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name="home"),
    path('user-type/', views.user_type, name='user_type'),
    path('login/', av.LoginView.as_view(template_name='auth.html'), name='auth'),
    path('logout/', av.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', register, name='register'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('Merch/', include('Merchandise.urls')),
    path('RegisterEvent/', include('RegisterEvent.urls')),
    path('Comments/', include('Comments.urls')),
    path('CreateEvent/', include('CreateEvent.urls')),
] 

Merchandise/models.py
from django.db import models
from CreateEvent.models import Event
# Create your models here.

class Merch(models.Model):
    event = models.ForeignKey(Event,related_name="merchandise", on_delete=models.CASCADE)
    name = models.CharField( max_length=50, null = True)
    Price = models.CharField( max_length=50, null = True)
    Picture = models.ImageField(null = True, blank=True)

    def __str__(self):
        return self.name

  

 

Merchandise/forms.py
from django.forms import ModelForm, TextInput, FileInput
from .models import Merch
from django.utils.translation import gettext_lazy as _

class MerchForm(ModelForm):
    class Meta:
        model = Merch
        fields = '__all__'
        exclude= ["event"]
        widgets = {
            "name": TextInput(attrs={"class":"form-control","placeholder": "Pensil", "required":True}),
            "Price": TextInput(attrs={"class":"form-control ","placeholder": "Rp. 1.000.000,00", "required":True}),
            "Picture": FileInput(attrs={"id":"imageinput","required":True})
        }

Merchandise/views.py
from django.shortcuts import render,redirect
from .forms import MerchForm
from CreateEvent.models import Event
from .models import Merch
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import JsonResponse,HttpResponse
# Create your views here.
@login_required(login_url=reverse_lazy('homepage:auth'))
def registerMerch(request, id):
    form = MerchForm()
    if request.method == "POST":
        form = MerchForm(request.POST or None ,request.FILES or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.event = Event.objects.get(id=id)
            obj.save()
            return redirect ('/Merch/ListMerch/'+str(id)+'/')
    context = {'form':form,
                  }
    return render(request, 'RegisterMerch.html',context)

@login_required(login_url=reverse_lazy('homepage:auth'))
def ajaxMerch(request,id):
    if request.method == 'POST':
        event = Event.objects.get(id=id)
        pic = request.FILES['Picture']
        nama =  request.POST['name']
        price = request.POST['Price']
        Merch.objects.create(
        event = event,
        name = nama,
        Price = price,
        Picture = pic
        )
        return HttpResponse('')
    context = { "id": id  }
    return render(request,'registermerchajax.html',context)


def displayMerch(request, id):
    event = Event.objects.get(id=id)
    Merch_list = event.merchandise.all()
    context = { 'event':event,'Merch_list':Merch_list  ,"id": id  }
    return render(request, 'ListMerch.html',context)

def MerchApi(request,id):
    event = Event.objects.get(id=id)
    Merch_list = event.merchandise.all()
    data ={"items":[]}
    for merch in Merch_list:
        pic = merch.Picture.url
        name = merch.name
        price = merch.Price
        data["items"].append({'pic':pic,'name':name,'price':price})
    return JsonResponse(data)
    

Merchandise/templates/ListMerch.html
{% extends 'baseMerch.html' %}

{% load crispy_forms_tags %}
{% load static %}



{% block tittle %}
<title>List-List Merchandise</title>
{% endblock %}

{% block content %}
<div class="banner">
    <h1 class ="ml2" >Merchandise</h1>
</div>
{% if event %}
{% if Merch_list.first == None %}
<div class="container">

  <div id="carouselExampleIndicators" class="carousel slide border border-dark" data-ride="carousel">
      <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
      </ol>
      <div class="carousel-inner carousel_1">
          <div class="carousel-item active" id="slide 1">
              <img src="https://img.icons8.com/pastel-glyph/64/000000/image--v1.png" class="d-block img">
              <div class="carousel_text   ">
                  <h4>Belum tersedia</h4>
                  <p>Rp. 0,00</p>
                </div>
          </div>
      </div>
      <h5 class="space"></h5>
      <div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a> 
      </div>
    </div>


{% else %}
<div class="container" >
  <div id="carouselExampleIndicators" class="carousel slide border border-dark" data-ride="carousel">
    <ol class="carousel-indicators">
        {% for j in Merch_list %}
      <li data-target="#carouselExampleIndicators" data-slide-to="[[forloop.counter}}" class="active"></li>
      {% endfor %}
    </ol>

    <div class="carousel-inner carousel_1" id="carouselbox">

    

  
  
</div>
<h5 class="space"></h5>
    <div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a> 
    </div>
</div>
{% endif %}
{% endif %}
{% if user.is_authenticated %}
<a href="{% url 'Merchandise:RegisterMerchAjax' id=event.id %}">
  <button type="button" class="btn btn-outline-secondary">Register Merchandise</button>
</a>
</div>
{% endif %}
{% endblock %}

{% block script%} 
<script  src="{% static 'js/srcipt.js' %}"></script>
<script>
$(document).ready(function(){
  var id = "{{ id }}"
  $.ajax({
    url:window.location.origin + "/Merch/ListMerch/json/" + id,
    dataType: "json",
    type: "GET",
    success:function(res){
      var carouselbox = $('#carouselbox')
      carouselbox.empty();
      console.log(res);
      
for(i=0;i<res['items'].length;i++){
  var picture = res['items'][i]['pic'];
  var name = res['items'][i]['name'];
  var price = res['items'][i]['price'];
  var active =""
  if(i+1==1)
  active="active";
  
var result =
      
      '<div class="carousel-item '+active +
      '" id="slide{{'+ i+' }}">'+
         ' <img src="'+picture+ '" class="d-block img">'
          +'<div class="carousel_text   ">'+
              '<h4>'+name+'</h4>'+
              '<p>'+price+'</p>'+
            '</div>'+
            '</div>'
;
      
      
  
  carouselbox.append(result);
}
    }
  })
})

</script>
{% endblock %}

Merchandise/templates/RegisterMerch.html
{% extends 'baseMerch.html' %}

{% load crispy_forms_tags %}
{% load static %}


{% block tittle %}
 <title>Daftar Merchandise</title>
{% endblock %}

{% block content %}

<div class="banner">
  <h1 class ="ml2" >Merchandise</h1>
</div>
<div class="container">
  <form  method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <div class = col-5>
            <div class="form-group">
                <label for="form_name">Nama Barang</label>
                {{form.name}}
              </div>
              <div class="form-group">
                <label for="form_Price">Harga Barang</label>
                {{form.Price}}
              </div>
              <div class="form-pic form-group border col-10">
                  <h1></h1>
                {{form.Picture}}
                <span id="capt">upload your image here!</span>
                <h6></h6>
              </div>
              <input class="btn btn-dark" type="submit" value="Submit">
        </div>
        
        
    </form>  
</div>



{% endblock %}

{% block script%} 
<script  src="{% static 'js/srcipt.js' %}"></script>
{% endblock %}



 

Merchandise/templates/baseMerch.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/merch.css' %}">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/base.css' %}">
        <script src="{% static 'js/base.js' %}" defer></script>
        <title>PEPEWIN</title>
    </head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-light" style="background: rgba(255, 255,255, 0.2);">
    <a class="navbar-brand" href="{% url 'homepage:home' %} " style="color: black;">LOGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:user_type' %}" style="color: black;">Events<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">About Us<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">Our Contacts</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <div class="custom-control custom-switch" id="cssMode" style="padding-top: 5%;">
          <input type="checkbox" class="custom-control-input" id="customSwitch1">
          <label class="custom-control-label" id="switch" for="customSwitch1"></label>
        </div>
        {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style="color: black;"> Hello, {{ user.username }} </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:logout' %}" style="color: black;">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:auth' %}" style="color: black;">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:register' %}" style="color: black;"> Register</a>
                </li>
            {% endif %}                      
      </ul>
    </div>
  </nav>




    {% block content %}
        
    {% endblock %}
     
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> 
<script src="https://cdn.jsdelivr.net/npm/animejs@3.0.1/lib/anime.min.js"></script>
{% block script%} 
{% endblock %}
</body>
</html>

Merchandise/templates/registermerchajax.html
{% extends 'baseMerch.html' %}

{% load crispy_forms_tags %}
{% load static %}


{% block tittle %}
 <title>Daftar Merchandise</title>
{% endblock %}

{% block content %}

<div class="banner">
  <h1 class ="ml2" >Merchandise</h1>
</div>
<div class="container">
  <form id="formUtama" method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <div class = col-5>
            <div class="form-group" >
                <label for="div_id_name" class="requiredField">Nama Barang</label>
                <input type="text" name="name" maxlength="50" class="form-control" required="" id="id_name" placeholder="pensil">
              </div>
              <div class="form-group">
                <label for="div_id_price" class="requiredField">Harga Barang</label>
                <input type="text" name="Price" maxlength="50" class="form-control" required="" id="id_price" placeholder="RP 1.000.000,00">
              </div>
              <div class="form-pic  form-group border col-10">
                  <h1></h1>
                  <input type="file" name="Picture" accept="image/*" class="clearablefileinput form-control-file" required="" id="imageinput"> 
                <span id="capt">upload your image here!</span>
                <h6></h6>
              </div>
              <input class="btn btn-dark" type="submit" value="Submit">
        </div>
        
        
    </form>  
</div>



{% endblock %}

{% block script%} 
<script type="text/javascript">
$(document).on("submit", "#formUtama", function (e){
    e.preventDefault();
    var id = "{{ id }}"
    var formutama2 = document.getElementById("formUtama");
    var formData = new FormData(formutama2);
    $.ajax({
        type:'POST',
        url: window.location.origin + "/Merch/RegisterMerchAjax/" + id+"/",
        data: formData,
        success:function(){
            $('#formUtama').trigger('reset');
            window.location.replace("/Merch/ListMerch/" +id+'/');
        },
        cache:false,
        contentType:false,
        processData:false,
    })
})
</script>
<script  src="{% static 'js/srcipt.js' %}"></script>
{% endblock %}