CreateEvent/urls.py
from django.urls import path
from . import views

app_name = 'CreateEvent'

urlpatterns = [
    path('', views.CreateEvent, name="indexCreate"),
    path('view/', views.ViewEvent, name="ViewEvent"),
    path('view/getEvents/', views.getEvents, name='getEvents'),

]

homepage/urls.py
from django.urls import path
from django.contrib.auth import views as av
from .views import register
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name="home"),
    path('user-type/', views.user_type, name='user_type'),
    path('login/', av.LoginView.as_view(template_name='auth.html'), name='auth'),
    path('logout/', av.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', register, name='register'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('Merch/', include('Merchandise.urls')),
    path('RegisterEvent/', include('RegisterEvent.urls')),
    path('Comments/', include('Comments.urls')),
    path('CreateEvent/', include('CreateEvent.urls')),
] 

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django.forms import ModelForm, TextInput, NumberInput
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password1','password2']

homepage/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

def home(request):
    return render(request, 'main.html')

def user_type(request):
    return render(request, 'user_type.html')

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}!')
            return redirect('homepage:auth')
    else:
        form = RegisterForm()
    context = {'form':form}
    return render(request,'register.html',{'form':form})

homepage/templates/auth.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<!-- <link rel="stylesheet" href="{% static 'css/auth.css' %}"> -->

<body>
    <br>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <form method = "POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-light" type="submit" value="Login">
        </form>
    </div>
</body>
{% endblock %}

{% block extra_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="" defer></script>
{% endblock extra_script %}
    

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/base.css' %}">
        <script src="{% static 'js/base.js' %}" defer></script>
        <title>PEPEWIN</title>
    </head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-light" style="background: rgba(255, 255,255, 0.2);">
    <a class="navbar-brand" href="{% url 'homepage:home' %} " style="color: black;">LOGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:user_type' %}" style="color: black;">Events<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">About Us<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">Our Contacts</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <div class="custom-control custom-switch" id="cssMode" style="padding-top: 5%;">
          <input type="checkbox" class="custom-control-input" id="customSwitch1">
          <label class="custom-control-label" id="switch" for="customSwitch1"></label>
        </div>
        {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style="color: black;"> Hello, {{ user.username }} </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:logout' %}" style="color: black;">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:auth' %}" style="color: black;">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:register' %}" style="color: black;"> Register</a>
                </li>
            {% endif %}                      
      </ul>
    </div>
  </nav>




    {% block content %}
        
    {% endblock %}
     
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
</body>
</html>

homepage/templates/index.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <style>
        .container{
            width: 100%;
        }
        .banner{
            width: 100%;
            height: 20vh;
            background-color: #2D9CDB;
        }
    </style>
    <body>
        <div class="banner"></div>
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-light" type="submit" value="Submit">
            </form> 
        </div>
    </body>
{% endblock %}

homepage/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<!-- <link rel="stylesheet" href="{% static 'css/auth.css' %}"> -->

<body>
    <br>
    <div class="container">
        <h2> You have been logged out</h2>
        <p> Click <a href="{% url 'homepage:auth' %}"> here to login again</p>
    </div>
</body>
{% endblock %}

{% block extra_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="" defer></script>
{% endblock extra_script %}
    

homepage/templates/main.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
</head>
<body style="background-image: url(https://files.catbox.moe/qai26i.svg);background-position: center;background-repeat: no-repeat;background-size: cover; background-color: #FFE3B8;"> -->


{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    body{
        background-image: linear-gradient(118deg, #80D0C7 0%, #13547A 98.85%);
        background-attachment: fixed;
    }
    .dark-mode {
        background-image: linear-gradient(118deg, #383686 0%, #13547A 98.85%);
        background-attachment: fixed;
    }
    .row{
        display: flex;
    }
    .col{
        text-align: center;
        width: 25%;
    }
    img{
        padding-bottom: 5%;
    }
</style> 

<link rel="stylesheet" href="{% static 'css/main.css' %}">
    
<body>
    <div class="container" style="height: auto; width: 100%;">
        <div class="container-fluid" style="text-align: center; padding-top: 10%;">
            <h1 style="font-size:6vh;font-family: montserrat; color: #ffffff;">Introduce Your Product <span><br></span> Quickly And Effectively</h1>
        </div>
        <div class="container-fluid" id="card" style="padding-top: 5%; width: 100%;">
            <div class="card" style="width: 100%; height: 100%;">
                <div class="card-body">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <img src="https://files.catbox.moe/0j0ar9.png" alt="">
                                <p style="padding-bottom: 1%; font-family: Mulish; font-weight: bold;">Business Dev</p>
                                <p>Introduce your business to potential stakeholders during this pandemic</p>
                            </div>
                            <div class="col">
                                <img src="https://files.catbox.moe/j67vpz.png" alt="">
                                <p style="padding-bottom: 1%;font-family: Mulish; font-weight: bold">Marketing</p>
                                <p>Market your brand even further during the pandemic</p>
                            </div>
                            <div class="col">
                                <img src="https://files.catbox.moe/5uugdq.png" alt="">
                                <p style="padding-bottom: 1%;font-family: Mulish; font-weight: bold;">Improve Events</p>
                                <p>Continue events with ease during the pandemic</p>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
        </div>
    </div>
</body> 

{% endblock %}

homepage/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="">
<body>
    <div class="container">
        <br>
        <form method = "POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-light" type="submit" value="Register">
        </form>

    </div>
</body>
{% endblock %}

{% block extra_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="" defer></script>
{% endblock extra_script %}

homepage/templates/user_type.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <style>
        h1{
            font-size: 8vw;
            font-family: Montserrat;
            color: #2F80ED;
        }
        .dark-mode {
        background-image: linear-gradient(118deg, #383686 0%, #13547A 98.85%);
        background-attachment: fixed;
        }
        .row{
            display: flex;
        }
        button{
            width: 100%;
        }
    </style>

<link rel="stylesheet" href="{% static 'css/user-type.css' %}">

    <div class="container">
        <div class="row">
            <div class="col">
                <h1>CHOOSE</h1>
                <br>
                <h1>YOUR</h1>
                <br>
                <h1>ROLE</h1>
                <br>
                <div class="row">
                    <div class="col-sm">
                        <a href="{% url 'CreateEvent:ViewEvent' %}">
                            <button type="button" class="btn btn-primary btn-lg">Event Attendees</button>
                        </a>
                    <br>
                    </div>
                    <div class="col-sm">
                        <a href="{% url 'CreateEvent:indexCreate' %}">
                            <button type="button" class="btn btn-outline-dark btn-lg">Event Host</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col" style="padding-left: 10%;">
                <img src="https://files.catbox.moe/uzwog5.png" alt="This text is shown if server fails to load image" />
            </div>
        </div>
    </div>
{% endblock %}