Comments/urls.py
from django.urls import path
from . import views

app_name = 'Comments'

urlpatterns = [
    path('<int:id>/', views.comments, name='Comments'),
    path ('<int:id>/data/',views.comments_data, name='Comments_data'),
    path('display/<int:id>/', views.displayComments, name='DisplayComments'),
    path ('display/<int:id>/data/',views.displayComments_data, name='DisplayComments_data'),
]

CreateEvent/urls.py
from django.urls import path
from . import views

app_name = 'CreateEvent'

urlpatterns = [
    path('', views.CreateEvent, name="indexCreate"),
    path('view/', views.ViewEvent, name="ViewEvent"),
    path('view/getEvents/', views.getEvents, name='getEvents'),

]

Merchandise/urls.py
from django.urls import path

from . import views

app_name = 'Merchandise'

urlpatterns = [
    path('RegisterMerch/<int:id>/', views.registerMerch, name='RegisterMerch'),
    path('ListMerch/<int:id>/', views.displayMerch, name='ListMerch'),
    path('ListMerch/json/<int:id>/', views.MerchApi, name='MerchJson'),
    path('RegisterMerchAjax/<int:id>/', views.ajaxMerch, name='RegisterMerchAjax'),

]

RegisterEvent/urls.py
from django.urls import path
from . import views

app_name = 'RegisterEvent'

urlpatterns = [
    path('<int:id>/', views.registerEvent, name="RegisterEvent"),
    path('display/<int:id>/', views.displayRegisterEvent, name="DisplayRegisterEvent"),
    path('json/<int:id>/', views.displayJson)
]

homepage/urls.py
from django.urls import path
from django.contrib.auth import views as av
from .views import register
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name="home"),
    path('user-type/', views.user_type, name='user_type'),
    path('login/', av.LoginView.as_view(template_name='auth.html'), name='auth'),
    path('logout/', av.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', register, name='register'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('Merch/', include('Merchandise.urls')),
    path('RegisterEvent/', include('RegisterEvent.urls')),
    path('Comments/', include('Comments.urls')),
    path('CreateEvent/', include('CreateEvent.urls')),
] 

CreateEvent/models.py
from django.db import models

# Create your models here.
class Event(models.Model) :
    Picture = models.ImageField(null = True, blank=True)
    eventName = models.CharField(max_length=80)
    description = models.CharField(max_length=250)
    eventDate = models.DateField()
    tempat = models.CharField(max_length=80)

    def __str__(self):
        return self.eventName

CreateEvent/forms.py
from django import forms
from django.forms import ModelForm, FileInput
from django.utils.translation import gettext_lazy as _

from .models import Event
class DateInput(forms.DateInput):
    input_type = 'date'

class CreateEventForm(ModelForm) :
    class Meta:
        model = Event
        fields = ['Picture', 'eventName', 'description', 'eventDate','tempat']

        widgets = {
            'Picture' : FileInput(attrs={"id":"imageinput","required":True}),
            'eventName' : forms.TextInput(attrs={"placeholder": "Covid fest", "required": True, "id" : "eventName"}),
            'description' : forms.TextInput(attrs={"placeholder": "Live Concert from Home", "required": True, "id" : "description"}),
            'eventDate': DateInput(),
            'tempat' : forms.TextInput(attrs={"placeholder": "Sabuga", "required": True, "id" : "tempat"}),

        }

    # eventName = forms.CharField(label='Event Name', max_length=80,
    #                                 widget=forms.TextInput(attrs={"placeholder": "Covid fest", "required": True}))

    # description  = forms.CharField(label='Description', max_length=250,
    #                                 widget=forms.TextInput(attrs={"placeholder": "Live Concert from Home", "required": True}))
    
    # eventDate = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    # # eventDate = forms.DateTimeField(
    # #     input_formats=['%d/%m/%Y %H:%M'],
    # #     widget=forms.DateTimeInput(attrs={
    # #         'class': 'form-control datetimepicker-input',
    # #         'id' : 'datetimepicker1',
    # #         'data-target': '#datetimepicker1'
    # #     })
    # # )

    # #eventDate  = forms.CharField(label='Event Date', max_length=80,
    #                                 #widget=forms.TextInput(attrs={"placeholder": "10 Januari 2019", "required": True}))
    # tempat  = forms.CharField(label='Location', max_length=80,
    #                                 widget=forms.TextInput(attrs={"placeholder": "Sabuga", "required": True})) 
    

CreateEvent/views.py
from django.shortcuts import render,redirect
from .forms import CreateEventForm
from .models import Event
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from django.http import HttpResponse, JsonResponse
import json

# @login_required(login_url=reverse_lazy('homepage:auth'))
# def CreateEvent(request):
#     my_form = CreateEventForm()

#     if request.method == 'POST':
#         my_form = CreateEventForm(request.POST or None ,request.FILES or None)
        
#         if my_form.is_valid():
#             Event.objects.create(**my_form.cleaned_data)
#             return redirect("CreateEvent:indexCreate")

#     context = {
#         'form' : my_form,
#     }
#     return render(request, "indexCreateAjax.html", context)   

# Create your views here.
@login_required(login_url=reverse_lazy('homepage:auth'))
def CreateEvent(request):
    my_form = CreateEventForm()
    response = {}
    if request.method == 'POST':
        if request.is_ajax():
            my_form = CreateEventForm(request.POST or None ,request.FILES or None)
            
            if my_form.is_valid():
                Event.objects.create(**my_form.cleaned_data)
                return JsonResponse({'success':True})
        return JsonResponse({'success':False})

    context = {
        'form' : my_form,
    }
    return render(request, "indexCreate.html", context)  

# @login_required(login_url=reverse_lazy('homepage:auth'))
# def eventMerch(request):
#     if request.method == 'POST':
#         pic = request.FILES['Picture']
#         nama =  request.POST['eventName']
#         desc = request.POST['description']
#         date = request.POST['eventDate']
#         tempat = request.POST['tempat']
#         Merch.objects.create(
#         Picture = pic
#         eventName = nama,
#         description = desc,
#         eventDate = date ,
#         tempat = tempat
#         )
#         return HttpResponse('')
#     # context = { "id": id  }
#     return render(request, "indexCreate.html")

def ViewEvent(request):
    events = Event.objects.all()

    context = {
        'events' : events
    }
    return render(request, "listEvent.html", context)  

def getEvents(request):
    userReq = Event.objects.all().values()
    lst = list(userReq)
    #print(lst)
    return JsonResponse(lst, safe=False)


# def model_form_upload(request):
#     if request.method == 'POST':
#         form = DocumentForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('home')
#     else:
#         form = DocumentForm()
#     return render(request, 'model_form_upload.html', {
#         'form': form
#     })

CreateEvent/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/base.css' %}">
        <title>PEPEWIN</title>
        <!-- Fengyuan Chen's Datepicker -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>

  <input id="datepicker">

  <script>
    $(function () {
      $("#datepicker").datepicker();
    });
  </script>

</body>
</html>


        
    </head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-light" style="background: rgba(255, 255,255, 0.2);">
    <a class="navbar-brand" href="#">LOGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'DaftarEvent:user_type' %}">Events<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">About Us<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Our Contacts</a>
        </li>
      </ul>
    </div>
  </nav>




    {% block content %}
        
    {% endblock %}
     
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
</body>
</html>

CreateEvent/templates/baseCreate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/base.css' %}">
        <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
        <script src="{% static 'js/base.js' %}" defer></script>
        <title>PEPEWIN</title>
    </head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-light" style="background: rgba(255, 255,255, 0.2);">
    <a class="navbar-brand" href="{% url 'homepage:home' %} " style="color: black;">LOGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:user_type' %}" style="color: black;">Events<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">About Us<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#" style="color: black;">Our Contacts</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <div class="custom-control custom-switch" id="cssMode" style="padding-top: 5%;">
          <input type="checkbox" class="custom-control-input" id="customSwitch1">
          <label class="custom-control-label" id="switch" for="customSwitch1"></label>
        </div>
        {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style="color: black;"> Hello, {{ user.username }} </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:logout' %}" style="color: black;">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:auth' %}" style="color: black;">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:register' %}" style="color: black;"> Register</a>
                </li>
            {% endif %}                      
      </ul>
    </div>
  </nav>




    {% block content %}
        
    {% endblock %}
     
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
</body>
</html>

CreateEvent/templates/indexCreate.html
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
{% extends 'baseCreate.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <style>
        .container{
            width: 100%;
        }
        .banner{
            width: 100%;
            height: 20vh;
            background-color: #2D9CDB;
        }

    </style>
    <body>
        <div class="banner"></div>
        <div class="container ">
            <form method="POST" enctype='multipart/form-data' id="createForm">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="button" class="tombol" id="submitBtn">Submit</button>
                <!-- <input type="submit" class="button-submit mx-auto" value="SUBMIT"> -->
            </form> 
            <div class="d-flex justify-content-center">
                <a role="button" class="button-create" href="{% url 'CreateEvent:ViewEvent' %}">VIEW </a>
            </div>
        </div>
        <!-- <script>
            $(function () {
              $("#id_date").datepicker({
                format:'dd/mm/yyyy',
              });
            });
          </script> -->
          <!-- <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script> -->
          <script>
            // console.log("QONITA KEPO");    
                    var input = document.getElementById('imageinput');
                    var infoArea = document.getElementById('capt');
                    input.addEventListener('change', showFileName);
                    function showFileName(event) {
                        // the change event gives us the input it occurred in 
                        var input = event.srcElement;
                        
                        // the input has an array of files in the `files` property, each one has a name that you can use. We're just using the name here.
                        var fileName = input.files[0].name;
        
                        // use fileName however fits your app best, i.e. add it into a div
                        infoArea.textContent = fileName;
                    }
        
                   
                    $(document).ready(function() {
                        $("#submitBtn").click(function() {
                            $.ajax({
                                type: "POST",
                                url: "/CreateEvent/",
                                data: $("#createForm").serialize(),
                                success: function(response) {
                                    $("#imageinput").val("")
                                    $("#eventName").val("")
                                    $("#eventDate").val("")
                                    $("#tempat").val("")
                                    // $("#input-event").trigger("keyup");
                                }
                            });
                        });
                    })
                
                    $(function () {
                        console.log("ini date")
                      $("#id_date").datepicker({
                        format:'dd/mm/yyyy',
                      });
                    });
         </script>

      
    </body>
    
{% endblock %}
{% block script %}
 <!-- <script>
    console.log("QONITA KEPO");    
			var input = document.getElementById('imageinput');
			var infoArea = document.getElementById('capt');
			input.addEventListener('change', showFileName);
			function showFileName(event) {
				// the change event gives us the input it occurred in 
				var input = event.srcElement;
				
				// the input has an array of files in the `files` property, each one has a name that you can use. We're just using the name here.
				var fileName = input.files[0].name;

				// use fileName however fits your app best, i.e. add it into a div
				infoArea.textContent = fileName;
            }

            // console.log("psospsps");  
        
            // console.log("aappppppppppp");
            // $("#submitBtn").click(function() {
            //     console.log("aaaaaaaaaaaaaaaaaaa");
            //     $.ajax({
            //         type: "POST",
            //         url: "/CreateEvent/",
            //         data: $("#createForm").serialize(),
            //         success: function(response) {
            //             $("#input-event").trigger("keyup");
            //         }
            //     });
            // });
           
        
            // $(function () {
            //     console.log("ini date")
            //   $("#id_date").datepicker({
            //     format:'dd/mm/yyyy',
            //   });
            // });
 </script> -->
 
 <script>
   
                    var input = document.getElementById('imageinput');
                    var infoArea = document.getElementById('capt');
                    input.addEventListener('change', showFileName);
                    function showFileName(event) {
                        // the change event gives us the input it occurred in 
                        var input = event.srcElement;
                        
                        // the input has an array of files in the `files` property, each one has a name that you can use. We're just using the name here.
                        var fileName = input.files[0].name;
        
                        // use fileName however fits your app best, i.e. add it into a div
                        infoArea.textContent = fileName;
                    }
 </script>

{% endblock %} 

CreateEvent/templates/listEvent.html
{% extends "baseCreate.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  

    
   
    {% if events.first != None %}

    <div class="row justify-content-center ">
      <div id="middleSection" style="margin-bottom: 30px;">
        <div class="ui search">
            <div class="ui icon input">
                <input id="input-event" class="prompt" type="text" placeholder="Search Event">
                <i class="search icon"></i>
            </div>
            <div class="results"></div>
        </div>
    </div>

        <div id= "message">
        {% for event in events %}
        <div class="card mb-4 mx-5 entry" style="width: 18rem;">
            {% if  event.Picture %}
            <img src="{{event.Picture.url}}" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <div class="row">
                <div class="col"> 
                  <h5 class="card-title">{{event.eventName}} </h5>
                </div>
                <div class="col"> 
                  <a href="{% url 'RegisterEvent:DisplayRegisterEvent' id=event.id %}">
                  <p style="text-align: right;">Attendees</p></a>
                </div>
              
              </div>
            
    
              <p class="card-text">{{ event.eventDate }}</p>
              <p class="card-text">{{ event.tempat }}</p>
              <p class="card-text">{{ event.description }}</p>
              <a href="{% url 'RegisterEvent:RegisterEvent' id=event.id %}">
                <button type="button" class="btn btn-outline-primary">Register</button>
             </a>
             <a href="{% url 'Comments:DisplayComments' id=event.id %}">
                <button type="button" class="btn btn-outline-secondary">Comments</button>
             </a>
             <a href="{% url 'Merchandise:ListMerch' id=event.id  %}">
                <p style="font-style: italic;font-size: small;">See Merchandises</p>
             </a>
             
            </div>
          </div>
          {% endfor %}
        </div>
   

    {% endif %}

  

   
       

    </div>

</div>

<script>
  $(function() {
      $('#input-event').keyup(function() {
          var keyword = $('#input-event').val();
          $.ajax({
              method: 'GET',
              url: 'getEvents/',
              dataType: 'json',
              success: function(data) {
                  $('#message').empty();
                  var html = '';
                  console.log("haiiiiiii")
                  if (data.length === 0) {
                      html += '<h3 class="txt-setting">We are sorry, there aren\'t any tips & trick.</h3>';
                      $('#message').append(html);
                  } else {
                      for (var i = 0; i < data.length; i++) {
                          if ((data[i]['eventName']).includes(keyword)) {
                              html += ' <div class="card mb-4 mx-5 entry" style="width: 18rem;">';
                              html = html + '<img>' + data[i]['Picture'] + '</img>';
                              html = html + '<h5>' + data[i]['eventName'] + '</h5>';
                              html = html + '<p>' + data[i]['description'] + '</p>';
                              html = html + '<p>' + data[i]['eventDate'] + '</p>';
                              html = html + '<p>' + data[i]['tempat'] + '</p>' + '</div>';
                          }
                      }
                      $('#message').append(html);
                      // console.log(data);
                  }
                  // console.log(data);
                  // console.log(data.length);
              }
          })
      })
  })
  
</script>


{% endblock content %}

CreateEvent/templates/model_form_upload.html
<!-- {% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %} -->